# Generated by Django 4.0.6 on 2023-08-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music_App', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('favorite', models.BooleanField(default=False)),
                ('desciption', models.TextField(max_length=150)),
                ('type', models.CharField(choices=[('Rap', 'Rap'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Hip-Hop', 'Hip-Hop')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_App.artists'),
        ),
    ]
