# Generated by Django 4.0.6 on 2023-08-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music_App', '0004_albums_artists_delete_album_delete_artist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
    ]
