# Generated by Django 4.0.6 on 2023-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_App', '0005_rename_albums_album_rename_artists_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='album',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('out of stock', 'out of stock')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
