# Generated by Django 4.0.6 on 2023-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_App', '0006_album_image_album_special_album_status_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=11)),
                ('subject', models.TextField(max_length=500)),
            ],
        ),
    ]
